### ISSUE TITLE
Silverstripe 3.5

### ISSUE THREAD

**Issue by roed** [wernerkrauss/silverstripe3-php7#1]
The patch doesn't work on my silverstripe 3.5.x installation. Should it?

**Comment by wernerkrauss** [comment]
"Doesn't work" isn't very helpful. Does the patch install? Do you get any errors with composer? What OS are you running on? What PHP-Version are you using in CLI for installing this patch?

**Comment by roed** [comment]
True, sorry :) What I meant is if it supposed to work.

Installing on ubuntu 14.04, php version 7.0.5-2+deb.sury.org~trusty+1 (cli). Sometimes it does work, so maybe there is something wrong with order of updating. Sorry, you can ignore this issue.
