### ISSUE TITLE
Could not apply patch

### ISSUE THREAD

**Issue by andreaslindahl** [wernerkrauss/silverstripe3-php7#3]
Is this still maintained? I'm running Silverstripe 3.6.2 and get "Could not apply patch" when adding this using Composer.

**Comment by wernerkrauss** [comment]
Yes, more or less. But in SilverStripe 3.6 this plugin / patch isn't needed any more as SS3.6 runs on PHP7 out of the box. 

So you can uninstall this module. Thanks for using it ;)

**Comment by andreaslindahl** [comment]
Ah, I see. Thanks! :)
